// Counterpart interactive demo: scenario data + play controller.
//
// Runs entirely client-side on the deterministic engine (counterpart-engine.js).
// The counterpart's replies come from per-persona banks keyed to the live
// emotional state. In production these banks are replaced by a local language
// model; the engine, the scoring, and this controller do not change.

(function () {
  "use strict";
  var E = window.CounterpartEngine;
  var MAX_TURNS = 7;

  // Optional live generation via a local LM Studio server. When reachable, the
  // counterpart's wording is generated by a local model instead of the canned
  // banks. The engine still decides every number; the model only phrases the
  // reply, guided by the current state. This exactly mirrors production. On the
  // public site (no local server, or https blocking http localhost) it stays
  // off and the canned banks run, so the demo works everywhere.
  var LIVE = {
    base: "http://localhost:1234/v1",
    model: "local-model", // replaced by whatever the local server reports
    available: false,
    on: false
  };

  // Short in-character identities used only in live mode.
  var SYSTEM = {
    clinical:
      "You are Margaret Doyle, 58, a teaching assistant, at your GP about headaches. You secretly stopped your blood-pressure tablets three weeks ago because they made you dizzy, and you are embarrassed about it. You are polite, apologetic, understated, working-class English. Never volunteer the tablets unless you are gently asked about medication or your daily routine.",
    contracting:
      "You are Darren Whitlock, 44, who runs a plumbing firm, angry about a change-order bill you are sure was always in scope. You are blunt, Northern English, and you talk in money and deadlines. Underneath it, cash is genuinely tight this quarter and you are embarrassed to admit it, so you hide it behind the anger.",
    management:
      "You are Priya Nair, 29, a software developer in a one-to-one about two missed deadlines. You are defensive, precise, and dry, and you hate being condescended to. You have secretly been covering a teammate's workload during their family crisis and you are burnt out, but saying so feels like an excuse, so you hold it back.",
    reception:
      "You are Ron Baxter, 67, retired, phoning a clinic reception, furious that your appointment has been cancelled three times. You are gruff and impatient and you repeat yourself when you feel unheard. Underneath the anger you are frightened, because it is a follow-up on a scan result, though you would never lead with that."
  };
  var LIVE_RULES =
    " Reply ONLY as this person, in the first person, under 40 words. No narration, no stage directions, no emoji, no quotation marks around your reply.";

  // ---- scenario library -------------------------------------------------
  // Each move carries a bounded UtteranceSignal. The skill the demo teaches:
  // build rapport first, ask the right question, and avoid the traps.
  var SCENARIOS = {
    clinical: {
      label: "Clinical",
      role: "clinician",
      you: "Clinician (you)",
      name: "Margaret Doyle",
      av: "M",
      avColor: "#8a5a2b",
      meta: "58 · presenting: headaches",
      behaviour: { openness: 3, agitation: 4, trust: 4, comprehension: 4, resistance: 55 },
      escalationTriggers: ["you should have", "just take", "quickly"],
      deescalationTriggers: ["not in trouble", "no rush", "take your time", "understandable"],
      disclosures: [
        { label: "She stopped her blood-pressure tablets", unlocksOn: ["medication", "tablets", "daily routine", "how are you managing"], requiresResistanceBelow: 40 },
        { label: "She fears a stroke, like her mother", unlocksOn: ["worried", "on your mind", "family", "what do you think"], requiresResistanceBelow: 46 }
      ],
      objectives: [
        { key: "used-open-questions", label: "Used open questions", weight: 1 },
        { key: "acknowledged-emotion", label: "Acknowledged her worry", weight: 1.5 },
        { key: "avoided-jargon", label: "Kept language plain", weight: 1 },
        { key: "elicited-hidden-concern", label: "Surfaced the real concern", weight: 2, critical: true }
      ],
      moves: [
        { label: "Ask an open question about how she's doing", sig: { open_question: true, topics: ["how are you"] } },
        { label: "Acknowledge how she's feeling", sig: { acknowledged_feeling: true, topics: ["worried", "on your mind"] } },
        { label: "Reassure her she's not in trouble", sig: { topics: ["not in trouble", "take your time"] } },
        { label: "Ask about her medication and daily routine", sig: { open_question: true, topics: ["medication", "tablets", "daily routine"] } },
        { label: "Explain the likely diagnosis in clinical terms", sig: { jargon_terms: ["hypertension", "CT angiogram"], topics: ["medication"] } },
        { label: "Press her for a straight answer", sig: { interrupted: true } }
      ],
      replies: {
        neutral: ["It's these headaches, they just won't shift. It's probably nothing.", "I didn't want to make a fuss, really."],
        guarded: ["I'm taking everything I'm meant to, yeah.", "Everything's fine at home. Just the headaches."],
        forthcoming: ["It's kind of you to ask. It has been on my mind.", "I suppose I've been worrying more than I let on."],
        upset: ["I knew I shouldn't have said anything. Can we leave it?", "It's fine, whatever you think is best. I don't want to waste your time."],
        unlock: [
          "Well... if I'm honest, I did stop the little blood-pressure ones. They made me ever so dizzy at work, and I felt daft ringing up.",
          "It's my mum, you see. She had a stroke. Every headache, I've been thinking the worst."
        ]
      }
    },

    contracting: {
      label: "Contracting",
      role: "contractor",
      you: "Contractor (you)",
      name: "Darren Whitlock",
      av: "D",
      avColor: "#3f5f7a",
      meta: "client · disputed change order",
      behaviour: { openness: 5, agitation: 7, trust: 3, comprehension: 6, resistance: 60 },
      escalationTriggers: ["it's in the contract", "small print", "not my problem", "as i said"],
      deescalationTriggers: ["let me show you", "walk you through", "you're right that", "fair point"],
      disclosures: [
        { label: "Cash flow is tight this quarter", unlocksOn: ["budget", "cash", "afford", "pressure", "what's really going on"], requiresResistanceBelow: 37 },
        { label: "A contractor once walked off his job", unlocksOn: ["trust", "before", "past experience", "worried we'd"], requiresResistanceBelow: 48 }
      ],
      objectives: [
        { key: "acknowledged-emotion", label: "Acknowledged his frustration", weight: 1.5 },
        { key: "used-open-questions", label: "Asked instead of restating the invoice", weight: 1 },
        { key: "avoided-jargon", label: "Did not hide behind contract-speak", weight: 1 },
        { key: "elicited-hidden-concern", label: "Surfaced the real pressure", weight: 2, critical: true }
      ],
      moves: [
        { label: "Acknowledge his frustration", sig: { acknowledged_feeling: true } },
        { label: "Ask what's really driving the reaction", sig: { open_question: true, topics: ["what's really going on", "pressure", "budget"] } },
        { label: "Offer to walk him through the original scope", sig: { topics: ["let me show you", "walk you through"] } },
        { label: "Point to the contract terms", sig: { topics: ["it's in the contract", "small print"] } },
        { label: "Explain the change-order accounting", sig: { jargon_terms: ["variation order", "accrual", "retention"], topics: ["budget"] } },
        { label: "Tell him to calm down", sig: { dismissed_concern: true } }
      ],
      replies: {
        neutral: ["Where's this extra come from? That was always part of it.", "I'm not being funny, but this is exactly what I said would happen."],
        guarded: ["Don't give me the contract line. Why did the number move?", "Everyone's got a reason. Doesn't change what lands on my desk."],
        forthcoming: ["Alright. If you can show me where it was signed off, I'll listen.", "Fair enough. I just don't want stitching up."],
        upset: ["You know what, forget it, I'll get someone else to finish it.", "Last time I use a firm I found online, I swear."],
        unlock: [
          "Look... between us, this quarter's been rough. A surprise like this genuinely hurts. I'm not made of money.",
          "I had a bloke walk off a job half-done once. Took the deposit with him. So I get funny about it."
        ]
      }
    },

    management: {
      label: "Management",
      role: "manager",
      you: "Manager (you)",
      name: "Priya Nair",
      av: "P",
      avColor: "#6a4a7a",
      meta: "direct report · two missed deadlines",
      behaviour: { openness: 3, agitation: 5, trust: 4, comprehension: 8, resistance: 58 },
      escalationTriggers: ["performance improvement", "on notice", "everyone else manages", "not good enough"],
      deescalationTriggers: ["not in trouble", "on your side", "how can i help", "not here to threaten", "sounds hard"],
      disclosures: [
        { label: "She's been covering a teammate and is burnt out", unlocksOn: ["what's been going on", "workload", "support", "outside of work", "how are you doing"], requiresResistanceBelow: 37 },
        { label: "She assumes she's being managed out", unlocksOn: ["not in trouble", "on your side", "want to help", "where is this going"], requiresResistanceBelow: 50 }
      ],
      objectives: [
        { key: "used-open-questions", label: "Opened with curiosity, not a verdict", weight: 1.5 },
        { key: "acknowledged-emotion", label: "Recognised the discomfort", weight: 1 },
        { key: "built-rapport", label: "Earned enough trust to stop the bracing", weight: 1 },
        { key: "elicited-hidden-concern", label: "Uncovered the hidden workload", weight: 2, critical: true }
      ],
      moves: [
        { label: "Open with curiosity, not a verdict", sig: { open_question: true, topics: ["what's been going on", "how are you doing"] } },
        { label: "Acknowledge this feels uncomfortable", sig: { acknowledged_feeling: true } },
        { label: "Reassure her she is not being managed out", sig: { topics: ["not in trouble", "on your side", "not here to threaten"] } },
        { label: "Ask about her workload and support", sig: { open_question: true, topics: ["workload", "support", "outside of work"] } },
        { label: "Bring up the performance-improvement process", sig: { topics: ["performance improvement", "on notice"] } },
        { label: "Say everyone else manages fine", sig: { dismissed_concern: true, topics: ["everyone else manages"] } }
      ],
      replies: {
        neutral: ["I know why we're here. The two deadlines.", "My output's down. I'm aware. I'll fix it."],
        guarded: ["It's fine. Nothing's going on. I just need to focus.", "If this is a formal thing, I'd rather just know now."],
        forthcoming: ["I didn't think anyone would take my side, so I stopped mentioning it.", "It's been a lot, honestly."],
        upset: ["So this is the part where you tell me it's a PIP. Great.", "I'd rather not get into it if the decision's already made."],
        unlock: [
          "Honestly? I've been carrying Sam's tickets since March, on top of mine. I didn't want to say anything. I'm running on empty.",
          "I walked in here sure this was step one of managing me out."
        ]
      }
    },

    reception: {
      label: "Reception",
      role: "member of staff",
      you: "Reception (you)",
      name: "Ron Baxter",
      av: "R",
      avColor: "#7a4a3a",
      meta: "caller · appointment cancelled 3 times",
      behaviour: { openness: 6, agitation: 8, trust: 2, comprehension: 5, resistance: 50 },
      escalationTriggers: ["hold", "another department", "policy", "calm down", "as i said", "system"],
      deescalationTriggers: ["that's on us", "i'll sort this", "here's what i'll do", "i'm listening", "leave it with me"],
      disclosures: [
        { label: "The appointment is a frightening scan follow-up", unlocksOn: ["what's the appointment for", "why it matters", "is everything okay", "sounds important"], requiresResistanceBelow: 42 }
      ],
      objectives: [
        { key: "acknowledged-emotion", label: "Acknowledged his frustration", weight: 1.5 },
        { key: "built-rapport", label: "De-escalated him to workable", weight: 1.5, critical: true },
        { key: "elicited-hidden-concern", label: "Understood the fear behind the anger", weight: 1.5 }
      ],
      moves: [
        { label: "Acknowledge his frustration and own it", sig: { acknowledged_feeling: true, topics: ["that's on us"] } },
        { label: "Take ownership and give one next step", sig: { topics: ["i'll sort this", "here's what i'll do", "leave it with me"] } },
        { label: "Ask what the appointment is for", sig: { open_question: true, topics: ["what's the appointment for", "is everything okay"] } },
        { label: "Explain the booking-system policy", sig: { topics: ["policy", "another department", "system"] } },
        { label: "Put him on a brief hold", sig: { topics: ["hold"] } },
        { label: "Tell him to calm down", sig: { dismissed_concern: true, topics: ["calm down"] } }
      ],
      replies: {
        neutral: ["Third time this week I'm ringing you lot. THIRD time.", "Is anyone actually there?"],
        guarded: ["I don't want sorry. Sorry doesn't get me an appointment.", "It's always another department. Nobody takes the blame."],
        forthcoming: ["...Alright. Alright. I suppose that's fair.", "You're actually listening. That's a first today."],
        upset: ["Forget it. Put me through to whoever's in charge.", "You're all the same, you lot."],
        unlock: [
          "It's a follow-up. On a scan. Every time you cancel it I'm sat here not knowing. I'm not angry at you, love. I'm scared, if you want the truth of it."
        ]
      }
    }
  };

  // ---- controller -------------------------------------------------------
  var cur = null; // current scenario key
  var scenario = null;
  var state = null;
  var over = false;
  var history = []; // {role, content} for live-mode continuity
  var busy = false;
  var session = 0; // bumped on scenario switch so a stale reply can't land

  function el(id) {
    return document.getElementById(id);
  }

  function rapport(s) {
    return Math.round(100 - s.resistance);
  }

  function moodBank(s) {
    if (s.agitation >= 6) return "upset";
    if (s.resistance >= 50) return "guarded";
    if (s.resistance < 33) return "forthcoming";
    return "neutral";
  }

  function pick(arr, seed) {
    return arr[seed % arr.length];
  }

  // ---- live generation (optional) --------------------------------------
  function stateProse(s) {
    var mood =
      s.agitation >= 7
        ? "You are upset and close to losing your temper."
        : s.agitation >= 4
        ? "You are tense and a little defensive."
        : "You are calm.";
    var guard =
      s.resistance >= 60
        ? "You do not trust this person yet. Keep your answers short and offer nothing you were not asked."
        : s.resistance >= 35
        ? "You are starting to warm up, but you are still holding the important thing back."
        : "You feel heard, and you are willing to open up.";
    return mood + " " + guard;
  }

  function cleanReply(txt) {
    if (!txt) return "";
    txt = txt.replace(/<think>[\s\S]*?<\/think>/gi, "");
    txt = txt.replace(/^["'\s]+|["'\s]+$/g, "");
    // keep it to a couple of sentences even if the model runs long
    var parts = txt.match(/[^.!?]+[.!?]+|[^.!?]+$/g);
    if (parts && parts.length > 3) txt = parts.slice(0, 3).join(" ").replace(/\s+/g, " ");
    return txt.trim();
  }

  function generateLive(nextState, justUnlocked) {
    var sys = SYSTEM[cur] + "\n\n" + stateProse(nextState);
    if (justUnlocked !== null && justUnlocked !== undefined) {
      sys +=
        "\n\nYou have just decided to admit this now, in your own words, naturally: " +
        scenario.disclosures[justUnlocked].label + ".";
    }
    sys += LIVE_RULES;

    var msgs = [{ role: "system", content: sys }].concat(history.slice(-6));
    var body = {
      model: LIVE.model,
      messages: msgs,
      temperature: 0.7,
      max_tokens: 90,
      stream: false
    };
    var ctrl = new AbortController();
    var timer = setTimeout(function () {
      ctrl.abort();
    }, 20000);
    return fetch(LIVE.base + "/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      signal: ctrl.signal
    })
      .then(function (r) {
        return r.json();
      })
      .then(function (d) {
        clearTimeout(timer);
        var c = d && d.choices && d.choices[0] && d.choices[0].message.content;
        c = cleanReply(c);
        if (!c) throw new Error("empty");
        return c;
      });
  }

  function probeLive() {
    // Only probe when the page is actually served from localhost (the local
    // product setup). From file:// or a public host the fetch would be blocked
    // and log a CORS error, so we skip it entirely and stay in canned mode.
    var host = location.hostname;
    if (!window.fetch) return;
    if (host !== "localhost" && host !== "127.0.0.1") return;
    var ctrl = new AbortController();
    setTimeout(function () {
      ctrl.abort();
    }, 2500);
    fetch(LIVE.base + "/models", { signal: ctrl.signal })
      .then(function (r) {
        return r.ok ? r.json() : null;
      })
      .then(function (d) {
        if (d && d.data && d.data.length) {
          LIVE.available = true;
          if (d.data[0].id) LIVE.model = d.data[0].id;
          var wrap = el("live-wrap");
          if (wrap) wrap.style.display = "inline-flex";
        }
      })
      .catch(function () {});
  }

  function toggleLive() {
    LIVE.on = !LIVE.on;
    var b = el("live-btn");
    if (b) {
      b.classList.toggle("on", LIVE.on);
      b.textContent = LIVE.on ? "Live · on" : "Live · off";
    }
  }

  function selectScenario(key) {
    cur = key;
    scenario = SCENARIOS[key];
    state = E.initialState(scenario);
    over = false;
    history = [];
    busy = false;
    session++;

    Array.prototype.forEach.call(document.querySelectorAll("#scenario-tabs .tab"), function (t) {
      t.classList.toggle("on", t.getAttribute("data-k") === key);
    });

    el("frame-title").innerHTML =
      "counterpart · <b>" + scenario.name + "</b> · " + scenario.label.toLowerCase() + " / difficult-conversation";
    el("transcript").innerHTML =
      '<div class="who">Counterpart · ' + scenario.name + " · " + scenario.meta + "</div>";
    el("debrief").classList.remove("show");

    buildLists();
    buildMoves();
    render();
    el("hint").textContent = "Turn 1 · pick a move";
  }

  function buildLists() {
    var disc = scenario.disclosures
      .map(function (d, i) {
        return '<li data-i="' + i + '"><span class="mk">/</span><span>' + d.label + "</span></li>";
      })
      .join("");
    el("disc").innerHTML = disc;

    var obj = scenario.objectives
      .map(function (o) {
        var crit = o.critical ? '<span class="crit">critical</span>' : "";
        return '<li data-k="' + o.key + '"><span class="mk">/</span><span>' + o.label + crit + "</span></li>";
      })
      .join("");
    el("obj").innerHTML = obj;
  }

  function buildMoves() {
    var html = scenario.moves
      .map(function (m, i) {
        return '<button class="move" data-i="' + i + '">' + m.label + "</button>";
      })
      .join("");
    el("moves").innerHTML = html;
    Array.prototype.forEach.call(el("moves").querySelectorAll(".move"), function (btn) {
      btn.addEventListener("click", function () {
        playMove(parseInt(btn.getAttribute("data-i"), 10));
      });
    });
  }

  function addMsg(cls, who, text) {
    var t = el("transcript");
    var d = document.createElement("div");
    d.className = "msg " + cls;
    // textContent, never innerHTML: in live mode this text comes from a model
    var w = document.createElement("p");
    w.className = "who";
    w.textContent = who;
    var b = document.createElement("div");
    b.className = "bubble";
    b.textContent = text;
    d.appendChild(w);
    d.appendChild(b);
    t.appendChild(d);
    requestAnimationFrame(function () {
      requestAnimationFrame(function () {
        d.classList.add("show");
      });
    });
    t.scrollTop = t.scrollHeight;
  }

  function cannedReply(next) {
    if (next.justUnlocked !== null) return scenario.replies.unlock[next.justUnlocked];
    return pick(scenario.replies[moodBank(next)], next.turn);
  }

  function playMove(i) {
    if (over || busy) return;
    busy = true; // one move at a time, canned or live
    var move = scenario.moves[i];
    addMsg("clin", scenario.you, cap(move.label));
    history.push({ role: "user", content: "[The professional chooses to: " + move.label + "]" });

    var next = E.advance(scenario, state, move.sig);
    state = next;
    var upset = next.agitation >= 6 ? " upset" : "";
    var mySession = session;

    function show(text) {
      if (mySession !== session) return; // scenario changed underneath us
      history.push({ role: "assistant", content: text });
      addMsg("pt" + upset, scenario.name, text);
      render();
      checkEnd();
      busy = false;
    }

    if (LIVE.on && LIVE.available) {
      var typing = addTyping();
      generateLive(next, next.justUnlocked)
        .then(function (text) {
          removeTyping(typing);
          show(text);
        })
        .catch(function () {
          removeTyping(typing);
          show(cannedReply(next)); // graceful fallback
        });
    } else {
      setTimeout(function () {
        show(cannedReply(next));
      }, 420);
    }
  }

  function addTyping() {
    var t = el("transcript");
    var d = document.createElement("div");
    d.className = "msg pt show";
    d.innerHTML = '<p class="who">' + scenario.name + '</p><div class="bubble typing">...</div>';
    t.appendChild(d);
    t.scrollTop = t.scrollHeight;
    return d;
  }
  function removeTyping(d) {
    if (d && d.parentNode) d.parentNode.removeChild(d);
  }

  function cap(s) {
    return s.charAt(0).toUpperCase() + s.slice(1) + ".";
  }

  function render() {
    var s = state;
    el("v-trust").textContent = s.trust.toFixed(1);
    el("v-agit").textContent = s.agitation.toFixed(1);
    el("v-rapport").textContent = rapport(s);
    el("f-trust").style.width = Math.round((s.trust / 10) * 100) + "%";
    el("f-agit").style.width = Math.round((s.agitation / 10) * 100) + "%";
    el("f-rapport").style.width = rapport(s) + "%";

    Array.prototype.forEach.call(el("disc").children, function (li) {
      var idx = parseInt(li.getAttribute("data-i"), 10);
      var on = s.unlocked.indexOf(idx) >= 0;
      li.classList.toggle("on", on);
      li.querySelector(".mk").textContent = on ? "●" : "/";
    });
    Array.prototype.forEach.call(el("obj").children, function (li) {
      var key = li.getAttribute("data-k");
      var met = s.met.indexOf(key) >= 0;
      li.classList.toggle("met", met);
      li.querySelector(".mk").textContent = met ? "✓" : "/";
    });

    var res = E.scoreSession(scenario, s);
    el("score").textContent = res.score;
    var v = el("verdict");
    if (over) {
      v.textContent = res.passed ? "Pass" : "Not yet";
      v.className = "verdict " + (res.passed ? "pass" : "fail");
    } else {
      v.textContent = "In progress";
      v.className = "verdict";
    }
  }

  function checkEnd() {
    var allMet = scenario.objectives.every(function (o) {
      return state.met.indexOf(o.key) >= 0;
    });
    if (allMet || state.turn >= MAX_TURNS) {
      over = true;
      render();
      showDebrief();
    } else {
      el("hint").textContent = "Turn " + (state.turn + 1) + " · pick a move";
    }
  }

  function showDebrief() {
    var res = E.scoreSession(scenario, state);
    el("debrief-score").textContent = res.score;
    var dv = el("debrief-verdict");
    dv.textContent = res.passed ? "PASS" : "NOT YET";
    dv.className = "debrief-verdict " + (res.passed ? "pass" : "fail");

    var lines = scenario.objectives
      .map(function (o) {
        var met = state.met.indexOf(o.key) >= 0;
        return (
          '<li class="' + (met ? "met" : "miss") + '"><span class="mk">' +
          (met ? "✓" : "✕") + "</span>" + o.label +
          (o.critical && !met ? ' <span class="crit">critical missed</span>' : "") + "</li>"
        );
      })
      .join("");
    el("debrief-list").innerHTML = lines;
    el("debrief-msg").textContent = res.passed
      ? "You built enough rapport to reach what was really going on. The same transcript would score the same for any assessor."
      : "The score is set by the engine, not the counterpart. Rebuild rapport before pushing for the hard answer, and try again.";
    el("debrief").classList.add("show");
    el("hint").textContent = "Session complete";
  }

  window.CounterpartDemo = {
    select: selectScenario,
    reset: function () {
      selectScenario(cur || "clinical");
    },
    toggleLive: toggleLive,
    scenarios: SCENARIOS
  };

  function boot() {
    selectScenario("clinical");
    probeLive();
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }
})();
