// Counterpart interactive demo: scenario data + play controller.
//
// Runs entirely client-side on the deterministic engine (counterpart-engine.js).
// You type what you would actually say; counterpart-signals.js turns the line
// into a bounded signal, the engine decides every number, and the reply is
// picked from per-persona banks keyed to what you did and how the counterpart
// now feels. In production a local language model does the annotation and the
// phrasing; the engine, the scoring, and this controller do not change.

(function () {
  "use strict";
  var E = window.CounterpartEngine;
  var S = window.CounterpartSignals;
  var MAX_TURNS = 7;

  // Optional live generation via a local LM Studio server. When reachable, the
  // counterpart's wording is generated by a local model instead of the banks.
  // The engine still decides every number. On the public site (no local
  // server) this never fires and the banks run, so the demo works everywhere.
  var LIVE = {
    base: "http://localhost:1234/v1",
    model: "local-model", // replaced by whatever the local server reports
    available: false,
    on: false
  };

  // Short in-character identities used only in live mode.
  var SYSTEM = {
    clinical:
      "You are Margaret Doyle, 58, a teaching assistant, at your GP about headaches. You secretly stopped your blood-pressure tablets three weeks ago because they made you dizzy, and you are embarrassed about it. You are polite, apologetic, understated, working-class English. Never volunteer the tablets unless you are gently asked about medication or your daily routine.",
    contracting:
      "You are Darren Whitlock, 44, who runs a plumbing firm, angry about a change-order bill you are sure was always in scope. You are blunt, Northern English, and you talk in money and deadlines. Underneath it, cash is genuinely tight this quarter and you are embarrassed to admit it, so you hide it behind the anger.",
    management:
      "You are Priya Nair, 29, a software developer in a one-to-one about two missed deadlines. You are defensive, precise, and dry, and you hate being condescended to. You have secretly been covering a teammate's workload during their family crisis and you are burnt out, but saying so feels like an excuse, so you hold it back.",
    reception:
      "You are Ron Baxter, 67, retired, phoning a clinic reception, furious that your appointment has been cancelled three times. You are gruff and impatient and you repeat yourself when you feel unheard. Underneath the anger you are frightened, because it is a follow-up on a scan result, though you would never lead with that."
  };
  var LIVE_RULES =
    " Reply ONLY as this person, in the first person, under 40 words. No narration, no stage directions, no emoji, no quotation marks around your reply.";

  // ---- scenario library -------------------------------------------------
  // Trigger phrase lists are written for typed language: they are matched as
  // substrings of whatever the trainee says, by the engine itself.
  var SCENARIOS = {
    clinical: {
      label: "Clinical",
      role: "clinician",
      you: "Clinician (you)",
      name: "Margaret Doyle",
      av: "M",
      avColor: "#8a5a2b",
      meta: "58 · presenting: headaches",
      behaviour: { openness: 3, agitation: 4, trust: 4, comprehension: 4, resistance: 55 },
      escalationTriggers: ["you should have", "just take", "hurry", "be quick"],
      deescalationTriggers: ["not in trouble", "no rush", "take your time", "understandable", "no need to be embarrassed"],
      jargon: ["hypertension", "angiogram", "idiopathic", "contraindicated", "neurovascular", "titrate", "cephalalgia"],
      disclosures: [
        { label: "She stopped her blood-pressure tablets", unlocksOn: ["medication", "tablets", "tablet", "pills", "meds", "prescription", "daily routine", "managing"], requiresResistanceBelow: 40 },
        { label: "She fears a stroke, like her mother", unlocksOn: ["worried", "on your mind", "family", "your mum", "your mother", "what do you think", "scares you", "frighten"], requiresResistanceBelow: 46 }
      ],
      objectives: [
        { key: "used-open-questions", label: "Used open questions", weight: 1 },
        { key: "acknowledged-emotion", label: "Acknowledged her worry", weight: 1.5 },
        { key: "avoided-jargon", label: "Kept language plain", weight: 1 },
        { key: "elicited-hidden-concern", label: "Surfaced the real concern", weight: 2, critical: true }
      ],
      prompts: [
        "How have things been for you in yourself lately?",
        "That sounds miserable, and I can see it's been wearing on you.",
        "You're not in trouble, take your time.",
        "How are you managing with your tablets day to day?"
      ],
      replies: {
        neutral: ["It's these headaches, they just won't shift. It's probably nothing.", "I didn't want to make a fuss, really.", "They come on most days now. I just get on with it."],
        guarded: ["I'm taking everything I'm meant to, yeah.", "Everything's fine at home. Just the headaches.", "I don't want to be a bother about it."],
        forthcoming: ["It's kind of you to ask. It has been on my mind.", "I suppose I've been worrying more than I let on."],
        upset: ["I knew I shouldn't have said anything. Can we leave it?", "It's fine, whatever you think is best. I don't want to waste your time."],
        bristle: ["Right. Sorry for troubling you, doctor.", "No, you're right. I'm sure it's silly."],
        warmed: ["That's kind of you. It has been getting me down, truth be told.", "Thank you. I didn't like to make a fuss of it."],
        answers: ["Most mornings, really. It starts behind my eyes and sits there all day.", "They come and go. Worse this last month, I'd say.", "Since about Easter, on and off."],
        puzzled: ["I'm sorry, doctor, you've lost me a bit there.", "I don't really follow all that, if I'm honest."],
        unlock: [
          "Well... if I'm honest, I did stop the little blood-pressure ones. They made me ever so dizzy at work, and I felt daft ringing up.",
          "It's my mum, you see. She had a stroke. Every headache, I've been thinking the worst."
        ]
      }
    },

    contracting: {
      label: "Contracting",
      role: "contractor",
      you: "Contractor (you)",
      name: "Darren Whitlock",
      av: "D",
      avColor: "#3f5f7a",
      meta: "client · disputed change order",
      behaviour: { openness: 5, agitation: 7, trust: 3, comprehension: 6, resistance: 60 },
      escalationTriggers: ["it's in the contract", "in the contract", "small print", "not my problem", "as i said", "read the terms"],
      deescalationTriggers: ["let me show you", "walk you through", "you're right that", "fair point", "line by line", "sit down with you"],
      jargon: ["variation order", "accrual", "retention", "provisional sum", "indemnity"],
      disclosures: [
        { label: "Cash flow is tight this quarter", unlocksOn: ["budget", "cash", "afford", "money side", "pressure", "tight", "what's really", "whats really"], requiresResistanceBelow: 37 },
        { label: "A contractor once walked off his job", unlocksOn: ["trust", "before", "past experience", "burned", "let down", "worried we"], requiresResistanceBelow: 48 }
      ],
      objectives: [
        { key: "acknowledged-emotion", label: "Acknowledged his frustration", weight: 1.5 },
        { key: "used-open-questions", label: "Asked instead of restating the invoice", weight: 1 },
        { key: "avoided-jargon", label: "Did not hide behind contract-speak", weight: 1 },
        { key: "elicited-hidden-concern", label: "Surfaced the real pressure", weight: 2, critical: true }
      ],
      prompts: [
        "I get why you're frustrated. A surprise bill is a surprise bill.",
        "What's really going on with this job for you?",
        "Let me show you where the change came from, line by line.",
        "Is the money side putting pressure on you this quarter?"
      ],
      replies: {
        neutral: ["Where's this extra come from? That was always part of it.", "I'm not being funny, but this is exactly what I said would happen."],
        guarded: ["Don't give me the contract line. Why did the number move?", "Everyone's got a reason. Doesn't change what lands on my desk."],
        forthcoming: ["Alright. If you can show me where it was signed off, I'll listen.", "Fair enough. I just don't want stitching up."],
        upset: ["You know what, forget it, I'll get someone else to finish it.", "Last time I use a firm I found online, I swear."],
        bristle: ["Don't talk to me like that, pal. I'm the customer here.", "Oh, that's how it is? Right."],
        warmed: ["Well. At least you're not pretending it's nothing.", "Fine. I'm listening."],
        answers: ["The number moved, that's what happened. Nobody rang me about it.", "All I know is the quote said one thing and the bill says another."],
        unlock: [
          "Look... between us, this quarter's been rough. A surprise like this genuinely hurts. I'm not made of money.",
          "I had a bloke walk off a job half-done once. Took the deposit with him. So I get funny about it."
        ]
      }
    },

    management: {
      label: "Management",
      role: "manager",
      you: "Manager (you)",
      name: "Priya Nair",
      av: "P",
      avColor: "#6a4a7a",
      meta: "direct report · two missed deadlines",
      behaviour: { openness: 3, agitation: 5, trust: 4, comprehension: 8, resistance: 58 },
      escalationTriggers: ["performance improvement", "on notice", "everyone else manages", "not good enough", "formal process"],
      deescalationTriggers: ["not in trouble", "on your side", "how can i help", "not here to threaten", "sounds hard", "not a formal"],
      jargon: [],
      disclosures: [
        { label: "She's been covering a teammate and is burnt out", unlocksOn: ["going on", "workload", "work load", "support", "outside of work", "how are you doing", "too much", "carrying", "on your plate"], requiresResistanceBelow: 37 },
        { label: "She assumes she's being managed out", unlocksOn: ["not in trouble", "on your side", "want to help", "where is this going", "not a formal"], requiresResistanceBelow: 50 }
      ],
      objectives: [
        { key: "used-open-questions", label: "Opened with curiosity, not a verdict", weight: 1.5 },
        { key: "acknowledged-emotion", label: "Recognised the discomfort", weight: 1 },
        { key: "built-rapport", label: "Earned enough trust to stop the bracing", weight: 1 },
        { key: "elicited-hidden-concern", label: "Uncovered the hidden workload", weight: 2, critical: true }
      ],
      prompts: [
        "What's been going on for you these last few weeks?",
        "I know sitting here must feel uncomfortable.",
        "You're not in trouble. I'm on your side here.",
        "How's your workload actually looking? Do you have support?"
      ],
      replies: {
        neutral: ["I know why we're here. The two deadlines.", "My output's down. I'm aware. I'll fix it."],
        guarded: ["It's fine. Nothing's going on. I just need to focus.", "If this is a formal thing, I'd rather just know now."],
        forthcoming: ["I didn't think anyone would take my side, so I stopped mentioning it.", "It's been a lot, honestly."],
        upset: ["So this is the part where you tell me it's a PIP. Great.", "I'd rather not get into it if the decision's already made."],
        bristle: ["Wow. Okay. Noted.", "That's easy to say from your side of the desk."],
        warmed: ["Thanks. I wasn't expecting that, honestly.", "Okay. That helps a bit."],
        answers: ["Short version? The estimates were fine. The time I actually had wasn't.", "Nothing's changed about my work. Something changed about my week."],
        unlock: [
          "Honestly? I've been carrying Sam's tickets since March, on top of mine. I didn't want to say anything. I'm running on empty.",
          "I walked in here sure this was step one of managing me out."
        ]
      }
    },

    reception: {
      label: "Reception",
      role: "member of staff",
      you: "Reception (you)",
      name: "Ron Baxter",
      av: "R",
      avColor: "#7a4a3a",
      meta: "caller · appointment cancelled 3 times",
      behaviour: { openness: 6, agitation: 8, trust: 2, comprehension: 5, resistance: 50 },
      escalationTriggers: ["on hold", "another department", "policy", "as i said", "the system says", "nothing i can do"],
      deescalationTriggers: ["that's on us", "i'll sort this", "here's what i'll do", "i'm listening", "leave it with me", "not passing you"],
      jargon: ["triage", "booking protocol", "patient pathway", "system migration"],
      disclosures: [
        { label: "The appointment is a frightening scan follow-up", unlocksOn: ["appointment for", "appointment is for", "what's it for", "what is it for", "why it matters", "everything okay", "everything ok", "sounds important", "what it's about"], requiresResistanceBelow: 42 }
      ],
      objectives: [
        { key: "acknowledged-emotion", label: "Acknowledged his frustration", weight: 1.5 },
        { key: "built-rapport", label: "De-escalated him to workable", weight: 1.5, critical: true },
        { key: "elicited-hidden-concern", label: "Understood the fear behind the anger", weight: 1.5 }
      ],
      prompts: [
        "You're right, that's on us. I can hear how upset you are.",
        "Here's what I'll do. I'm not passing you anywhere else.",
        "Leave it with me. I'll sort this today.",
        "Can I ask what the appointment is for? It sounds important."
      ],
      replies: {
        neutral: ["Third time this week I'm ringing you lot. THIRD time.", "Is anyone actually there?"],
        guarded: ["I don't want sorry. Sorry doesn't get me an appointment.", "It's always another department. Nobody takes the blame."],
        forthcoming: ["...Alright. Alright. I suppose that's fair.", "You're actually listening. That's a first today."],
        upset: ["Forget it. Put me through to whoever's in charge.", "You're all the same, you lot."],
        bristle: ["Don't you tell me to settle down. Three times, love. THREE.", "Oh, here we go. Same script every time."],
        warmed: ["...Well. That's something, I suppose.", "First one of you lot to say that like you mean it."],
        answers: ["Tuesday it was. Then the Thursday. Then this morning, gone again.", "I've been ringing since nine. Keep getting passed about."],
        puzzled: ["I don't care what the system's called, I care about my appointment.", "That means nothing to me, that."],
        unlock: [
          "It's a follow-up. On a scan. Every time you cancel it I'm sat here not knowing. I'm not angry at you, love. I'm scared, if you want the truth of it."
        ]
      }
    }
  };

  // ---- controller -------------------------------------------------------
  var cur = null; // current scenario key
  var scenario = null;
  var state = null;
  var over = false;
  var history = []; // {role, content} for live-mode continuity
  var busy = false;
  var session = 0; // bumped on scenario switch so a stale reply can't land
  var bankCursor = {}; // per-bank rotation so replies don't repeat back to back

  function el(id) {
    return document.getElementById(id);
  }

  function rapport(s) {
    return Math.round(100 - s.resistance);
  }

  function moodBank(s) {
    if (s.agitation >= 6) return "upset";
    if (s.resistance >= 50) return "guarded";
    if (s.resistance < 33) return "forthcoming";
    return "neutral";
  }

  function pickVaried(bankName, arr) {
    var i = bankCursor[bankName] || 0;
    bankCursor[bankName] = i + 1;
    return arr[i % arr.length];
  }

  // The reply reacts to the strongest thing you just did, then falls back to
  // the counterpart's current mood. Deterministic, like everything else here.
  function composeReply(next, sig) {
    var R = scenario.replies;
    if (next.justUnlocked !== null) return R.unlock[next.justUnlocked];
    if (sig.dismissed_concern && R.bristle) return pickVaried("bristle", R.bristle);
    if (sig.jargon_terms && sig.jargon_terms.length && scenario.behaviour.comprehension < 6 && R.puzzled)
      return pickVaried("puzzled", R.puzzled);
    if (next.agitation >= 6) return pickVaried("upset", R.upset);
    if (sig.acknowledged_feeling && R.warmed) return pickVaried("warmed", R.warmed);
    if (sig.open_question && R.answers) return pickVaried("answers", R.answers);
    var bank = moodBank(next);
    return pickVaried(bank, R[bank]);
  }

  // ---- live generation (optional) --------------------------------------
  function stateProse(s) {
    var mood =
      s.agitation >= 7
        ? "You are upset and close to losing your temper."
        : s.agitation >= 4
        ? "You are tense and a little defensive."
        : "You are calm.";
    var guard =
      s.resistance >= 60
        ? "You do not trust this person yet. Keep your answers short and offer nothing you were not asked."
        : s.resistance >= 35
        ? "You are starting to warm up, but you are still holding the important thing back."
        : "You feel heard, and you are willing to open up.";
    return mood + " " + guard;
  }

  function cleanReply(txt) {
    if (!txt) return "";
    txt = txt.replace(/<think>[\s\S]*?<\/think>/gi, "");
    txt = txt.replace(/^["'\s]+|["'\s]+$/g, "");
    // keep it to a couple of sentences even if the model runs long
    var parts = txt.match(/[^.!?]+[.!?]+|[^.!?]+$/g);
    if (parts && parts.length > 3) txt = parts.slice(0, 3).join(" ").replace(/\s+/g, " ");
    return txt.trim();
  }

  function generateLive(nextState, justUnlocked) {
    var sys = SYSTEM[cur] + "\n\n" + stateProse(nextState);
    if (justUnlocked !== null && justUnlocked !== undefined) {
      sys +=
        "\n\nYou have just decided to admit this now, in your own words, naturally: " +
        scenario.disclosures[justUnlocked].label + ".";
    }
    sys += LIVE_RULES;

    var msgs = [{ role: "system", content: sys }].concat(history.slice(-6));
    var body = {
      model: LIVE.model,
      messages: msgs,
      temperature: 0.7,
      max_tokens: 90,
      stream: false
    };
    var ctrl = new AbortController();
    var timer = setTimeout(function () {
      ctrl.abort();
    }, 20000);
    return fetch(LIVE.base + "/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      signal: ctrl.signal
    })
      .then(function (r) {
        return r.json();
      })
      .then(function (d) {
        clearTimeout(timer);
        var c = d && d.choices && d.choices[0] && d.choices[0].message.content;
        c = cleanReply(c);
        if (!c) throw new Error("empty");
        return c;
      });
  }

  function probeLive() {
    // Only probe when the page is actually served from localhost (the local
    // product setup). From file:// or a public host the fetch would be blocked
    // and log a CORS error, so we skip it entirely and stay in canned mode.
    var host = location.hostname;
    if (!window.fetch) return;
    if (host !== "localhost" && host !== "127.0.0.1") return;
    var ctrl = new AbortController();
    setTimeout(function () {
      ctrl.abort();
    }, 2500);
    fetch(LIVE.base + "/models", { signal: ctrl.signal })
      .then(function (r) {
        return r.ok ? r.json() : null;
      })
      .then(function (d) {
        if (d && d.data && d.data.length) {
          LIVE.available = true;
          if (d.data[0].id) LIVE.model = d.data[0].id;
          var wrap = el("live-wrap");
          if (wrap) wrap.style.display = "inline-flex";
        }
      })
      .catch(function () {});
  }

  function toggleLive() {
    LIVE.on = !LIVE.on;
    var b = el("live-btn");
    if (b) {
      b.classList.toggle("on", LIVE.on);
      b.textContent = LIVE.on ? "Live · on" : "Live · off";
    }
  }

  function selectScenario(key) {
    cur = key;
    scenario = SCENARIOS[key];
    state = E.initialState(scenario);
    over = false;
    history = [];
    busy = false;
    session++;
    bankCursor = {};

    Array.prototype.forEach.call(document.querySelectorAll("#scenario-tabs .tab"), function (t) {
      t.classList.toggle("on", t.getAttribute("data-k") === key);
    });

    el("frame-title").innerHTML =
      "counterpart · <b>" + scenario.name + "</b> · " + scenario.label.toLowerCase() + " / difficult-conversation";
    el("transcript").innerHTML =
      '<div class="who">Counterpart · ' + scenario.name + " · " + scenario.meta + "</div>";
    el("debrief").classList.remove("show");

    var input = el("say");
    if (input) input.value = "";
    renderHeard(null);
    buildLists();
    buildPrompts();
    render();
    el("hint").textContent = "Turn 1 of " + MAX_TURNS;
  }

  function buildLists() {
    var disc = scenario.disclosures
      .map(function (d, i) {
        return '<li data-i="' + i + '"><span class="mk">/</span><span>' + d.label + "</span></li>";
      })
      .join("");
    el("disc").innerHTML = disc;

    var obj = scenario.objectives
      .map(function (o) {
        var crit = o.critical ? '<span class="crit">critical</span>' : "";
        return '<li data-k="' + o.key + '"><span class="mk">/</span><span>' + o.label + crit + "</span></li>";
      })
      .join("");
    el("obj").innerHTML = obj;
  }

  function buildPrompts() {
    var box = el("prompts");
    box.innerHTML = "";
    scenario.prompts.forEach(function (p) {
      var b = document.createElement("button");
      b.type = "button";
      b.className = "prompt";
      b.textContent = p;
      b.addEventListener("click", function () {
        var input = el("say");
        input.value = p;
        input.focus();
      });
      box.appendChild(b);
    });
  }

  function renderHeard(heard) {
    var box = el("heard");
    if (!box) return;
    box.innerHTML = "";
    if (!heard) {
      var note = document.createElement("span");
      note.className = "signote";
      note.textContent = "signals read from your last line show here";
      box.appendChild(note);
      return;
    }
    var lbl = document.createElement("span");
    lbl.className = "signote";
    lbl.textContent = "engine heard:";
    box.appendChild(lbl);
    heard.forEach(function (h) {
      var c = document.createElement("span");
      c.className = "sigchip";
      c.textContent = h;
      box.appendChild(c);
    });
  }

  function addMsg(cls, who, text) {
    var t = el("transcript");
    var d = document.createElement("div");
    d.className = "msg " + cls;
    // textContent, never innerHTML: this text is typed by the visitor or, in
    // live mode, produced by a model
    var w = document.createElement("p");
    w.className = "who";
    w.textContent = who;
    var b = document.createElement("div");
    b.className = "bubble";
    b.textContent = text;
    d.appendChild(w);
    d.appendChild(b);
    t.appendChild(d);
    requestAnimationFrame(function () {
      requestAnimationFrame(function () {
        d.classList.add("show");
      });
    });
    t.scrollTop = t.scrollHeight;
  }

  function playText(text) {
    text = String(text || "").trim();
    if (over || busy || !text) return;
    busy = true; // one line at a time, canned or live
    addMsg("clin", scenario.you, text);
    history.push({ role: "user", content: text });

    var read = S.read(text, scenario);
    renderHeard(read.heard);

    var next = E.advance(scenario, state, read.signal);
    state = next;
    var upset = next.agitation >= 6 ? " upset" : "";
    var mySession = session;

    function show(reply) {
      if (mySession !== session) return; // scenario changed underneath us
      history.push({ role: "assistant", content: reply });
      addMsg("pt" + upset, scenario.name, reply);
      render();
      checkEnd();
      busy = false;
    }

    if (LIVE.on && LIVE.available) {
      var typing = addTyping();
      generateLive(next, next.justUnlocked)
        .then(function (reply) {
          removeTyping(typing);
          show(reply);
        })
        .catch(function () {
          removeTyping(typing);
          show(composeReply(next, read.signal)); // graceful fallback
        });
    } else {
      setTimeout(function () {
        show(composeReply(next, read.signal));
      }, 420);
    }
  }

  function addTyping() {
    var t = el("transcript");
    var d = document.createElement("div");
    d.className = "msg pt show";
    d.innerHTML = '<p class="who">' + scenario.name + '</p><div class="bubble typing">...</div>';
    t.appendChild(d);
    t.scrollTop = t.scrollHeight;
    return d;
  }
  function removeTyping(d) {
    if (d && d.parentNode) d.parentNode.removeChild(d);
  }

  function render() {
    var s = state;
    el("v-trust").textContent = s.trust.toFixed(1);
    el("v-agit").textContent = s.agitation.toFixed(1);
    el("v-rapport").textContent = rapport(s);
    el("f-trust").style.width = Math.round((s.trust / 10) * 100) + "%";
    el("f-agit").style.width = Math.round((s.agitation / 10) * 100) + "%";
    el("f-rapport").style.width = rapport(s) + "%";

    Array.prototype.forEach.call(el("disc").children, function (li) {
      var idx = parseInt(li.getAttribute("data-i"), 10);
      var on = s.unlocked.indexOf(idx) >= 0;
      li.classList.toggle("on", on);
      li.querySelector(".mk").textContent = on ? "●" : "/";
    });
    Array.prototype.forEach.call(el("obj").children, function (li) {
      var key = li.getAttribute("data-k");
      var met = s.met.indexOf(key) >= 0;
      li.classList.toggle("met", met);
      li.querySelector(".mk").textContent = met ? "✓" : "/";
    });

    var res = E.scoreSession(scenario, s);
    el("score").textContent = res.score;
    var v = el("verdict");
    if (over) {
      v.textContent = res.passed ? "Pass" : "Not yet";
      v.className = "verdict " + (res.passed ? "pass" : "fail");
    } else {
      v.textContent = "In progress";
      v.className = "verdict";
    }
  }

  function checkEnd() {
    var allMet = scenario.objectives.every(function (o) {
      return state.met.indexOf(o.key) >= 0;
    });
    if (allMet || state.turn >= MAX_TURNS) {
      over = true;
      render();
      showDebrief();
    } else {
      el("hint").textContent = "Turn " + (state.turn + 1) + " of " + MAX_TURNS;
    }
  }

  function showDebrief() {
    var res = E.scoreSession(scenario, state);
    el("debrief-score").textContent = res.score;
    var dv = el("debrief-verdict");
    dv.textContent = res.passed ? "PASS" : "NOT YET";
    dv.className = "debrief-verdict " + (res.passed ? "pass" : "fail");

    var lines = scenario.objectives
      .map(function (o) {
        var met = state.met.indexOf(o.key) >= 0;
        return (
          '<li class="' + (met ? "met" : "miss") + '"><span class="mk">' +
          (met ? "✓" : "✕") + "</span>" + o.label +
          (o.critical && !met ? ' <span class="crit">critical missed</span>' : "") + "</li>"
        );
      })
      .join("");
    el("debrief-list").innerHTML = lines;
    el("debrief-msg").textContent = res.passed
      ? "You built enough rapport to reach what was really going on. The same transcript would score the same for any assessor."
      : "The score is set by the engine, not the counterpart. Rebuild rapport before pushing for the hard answer, and try again.";
    el("debrief").classList.add("show");
    el("hint").textContent = "Session complete";
  }

  window.CounterpartDemo = {
    select: selectScenario,
    reset: function () {
      selectScenario(cur || "clinical");
    },
    toggleLive: toggleLive,
    say: playText,
    scenarios: SCENARIOS
  };

  function boot() {
    var form = el("say-form");
    if (form) {
      form.addEventListener("submit", function (e) {
        e.preventDefault();
        var input = el("say");
        playText(input.value);
        input.value = "";
        input.focus();
      });
    }
    selectScenario("clinical");
    probeLive();
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }
})();
